name: minishop-microservice-e-commerce-system

services:
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile

    container_name: minishop-admin-panel

    env_file:
      - ./admin/.env

    ports:
      - "3000:3000"

    networks:
      - minishop-network
  user:
    build:
      context: ./user
      dockerfile: Dockerfile

    container_name: minishop-user-panel

    env_file:
      - ./user/.env

    ports:
      - "3010:3000"

    networks:
      - minishop-network
  user_service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile

    container_name: minishop-user-service

    env_file:
      - ./services/user-service/.env

    ports:
      - "3001:3001"

    networks:
      - minishop-network

  product_service:
    build:
      context: ./services/product-service
      dockerfile: Dockerfile

    container_name: minishop-product-service

    env_file:
      - ./services/product-service/.env

    ports:
      - "3002:3002"

    networks:
      - minishop-network
      
volumes:
  kafka-data:

networks:
  minishop-network:
    driver: bridge
