name: Product Service CI

on:
  push:
    paths:
      - 'services/product-service/**'
      - 'sonar-project.properties'

  pull_request:
    paths:
      - 'services/product-service/**'
      - 'sonar-project.properties'

jobs:
  notification-ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/product-service

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: services/product-service/package.json

      - name: Install dependencies
        run: npm install

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
